# COGS 108 - Data Checkpoint

## Authors

- Fiona Bean: Methodology, Background Research, Writing– Original Draft, Writing- Review & Editing
- Julia Miranda: Writing– Original Draft, Methodology, Writing- Review & Editing 
- Grace Osueke: Data Curation, Software
- Jake Recore: Writing– Review & Editing, Data Curation, Methodology
- Emmy Shirokova: Methodology, Writing- Review & Editing, Supervision

## Research Question

Our research question is: using questionnaire data, to what extent are chronotype and sleep quality factors associated with GPA among college students? This study will ask students to self-report information pertaining to sleep habits, demographic factors, and other lifestyle variables that are relevant in assessing sleep and chronotype factors’ correlations with academic performance. This study will use inferential statistics, mainly multiple regression and ANOVA tests, to assess the proportion of variance in GPA that directly correlates with sleep quality and chronotype. (Variables used are discussed more in-depth in the ‘Data’ section)

## Background and Prior Work

Sleep has been shown to play a critical role in cognitive functioning, memory consolidation, and learning, all of which are essential for academic success. Prior research has consistently shown that sleep deprivation is associated with lower academic performance (GPA) among college students (Hershner & Chervin, 2014). Incorporating this into our design, we recognize that sleep is a multidimensional construct that includes more than just sleep duration as a significant predictor of overall sleep quality. As a result, this study aims to reinforce the literature on other sleep subvariables’ associations with academic performance among college students. Along with the quantity of sleep, the continuity, variability, and timing of sleep periods are also essential factors in assessing sleep health (Buysse, 2014). 

Related to sleep timing is chronotype, which refers to an individual’s natural preference for activity at certain times of day influenced by genetic and environmental factors. Oftentimes, there exists a misalignment between inflexible scheduled activities, such as work and school, and natural chronotype preferences. This mismatch between natural chronotype and work/school schedules is referred to as “social jetlag” (Wittmann et al., 2009). We represent this construct as the difference between the sleep midpoint on free days versus work/school days. The presence of social jetlag has been linked to poorer academic outcomes and reduced wellbeing, as reduced sleep quality on working days is compensated for by increased sleep duration on non-working days, thus creating harmful inconsistencies in long-term sleep schedule. 

This study aims to combine multidimensional measures of sleep quality with chronotype category to assess the extent to which each variable predicts academic performance. In order to better isolate these variables from potential confounds, caffeine consumption and phone usage before bed will be recorded from participants, as both of these effects have known effects on delaying circadian rhythms and interfering with sleep quality measures. Demographic variables, particularly age and sex, are also related to chronotype expression (Roennenberg, 2012). Our model of chronotype and sleep quality will account for these influencing variables to ensure accuracy in detecting an independent effect of chronotype on GPA.

## Hypothesis

We hypothesize that sleep behavior and chronotype alignment will significantly predict academic performance (GPA) among college students. "Perceived chronotype" refers to an individual's subjective experience of their internal biological clock. It dictates natural preferences for sleep and wakefulness. In our study, we predict that students who report 7-9 hours of sleep per night will have a higher GPA compared to those with shorter or longer sleep duration. We further hypothesize that greater chronotype mismatch, defined as the discrepancy between preferred sleep timing and actual daily schedules, will be associated with lower GPA. Additionally, we predict that later sleep onset times will negatively relate to GPA due misalignment with typical academic schedules. Finally, we hypothesize that these effects will be moderated by academic context, with stronger negative impacts observed among STEM majors and upper-division students. 

We predict that students who experience greater mismatch between their preferred sleep schedules and their actual weekday sleep schedules, along with lower sleep consistency and poorer overall sleep habits, will tend to report lower GPAs. In contrast, students whose sleep patterns are more aligned with their weekday academic schedules are expected to report stronger academic performance overall.

## Data

### Data overview

- Dataset Name: COGS108 Chronotype Survey 
- Link to the questionnaire: https://ucsd.co1.qualtrics.com/jfe/form/SV_2rFipSzXLOxeh70
- Number of observations: We currently have 74 total responses (as of 5/13/26 8PM). The survey is still active.
- Number of variables: We have 9 variables that operationalize chronotype, sleep quality, academic performance, and potential confounds..
Description of the variables most relevant to this project: The dataset includes variables measuring average bedtime and wake time on work or school days, preferred bedtime and wake time on days without commitments, sleep consistency, nighttime awakenings, time required to fall asleep, caffeine consumption before bed, phone usage before sleep, GPA, major category, extracurricular workload, age and sex. Chronotype mismatch will be operationalized as the difference between participants’ preferred sleep schedules on days without commitments and their actual sleep schedules during work or school days. Caffeine consumption, phone usage before bed, and extracurricular load are being collected as confounds that affect sleep quality other than chronotype mismatch. Nighttime awakenings, time required to fall asleep, and consistency of sleep will be collected as variables to describe sleep quality. We will use chronotype mismatch to try and predict GPA, and see if this prediction strengthens/weakens when considering confounds like caffeine and phone usage before bed. Additionally, we will explore how involvement in extracurriculars, age, and sex, affect sleep quality and/or GPA.  
- Descriptions of any shortcomings this dataset has with respect to the project: The dataset relies on self-reported surveys, which may introduce recall bias and self-report bias. GPA is self-reported and cannot be independently verified. Additionally, the study uses cross- sectional survey data rather than longitudinal sleep tracking or wearable sleep-monitoring devices, limiting the ability to establish causation between sleep behavior and academic performance. The sample may not fully generalize to all undergraduate student populations because participation is voluntary and recruitment is conducted primarily through online distribution methods. 
- Description of ideal dataset: collection would include accurate sleep data over multiple weeks/months, confirmed by a sleep tracking device such as a fitbit or apple watch; which would optimize and generate automatic recorded sleep onset and wakeup times. We would ideally want a verified GPA/transcript data instead of self-reported GPA, a larger more diverse undergraduate sample group, exact class schedule timing, as well as iphone and caffeine tracking. Lastly, our ideal sample would be a random sample of all undergraduate college students.

In [1]:
# Run this code every time when you're actively developing modules in .py files.  It's not needed if you aren't making modules
#
## this code is necessary for making sure that any modules we load are updated here 
## when their source code .py files are modified

%load_ext autoreload
%autoreload 2

In [2]:
# Setup code -- this only needs to be run once after cloning the repo!
# this code downloads the data from its source to the `data/00-raw/` directory
# if the data hasn't updated you don't need to do this again!

# if you don't already have these packages (you should!) uncomment this line
# %pip install requests tqdm

import sys
sys.path.append('./modules') # this tells python where to look for modules to import

import get_data # this is where we get the function we need to download data

# replace the urls and filenames in this list with your actual datafiles
# yes you can use Google drive share links or whatever
# format is a list of dictionaries; 
# each dict has keys of 
#   'url' where the resource is located
#   'filename' for the local filename where it will be stored 
datafiles = [
    { 'url': 'https://raw.githubusercontent.com/COGS108/Group-SP26-010/refs/heads/main/data/00-raw/COGS108ChronotypeSurvey.csv?token=GHSAT0AAAAAAD2FFZXLFJUC4CDSALS25NOG2QFETTQ', 'filename':'COGS108ChronotypeSurvey.csv'},
]

get_data.get_raw(datafiles,destination_directory='data/00-raw/')

Overall Download Progress: 100%|██████████| 1/1 [00:00<00:00,  6.16it/s]

Error downloading COGS108ChronotypeSurvey.csv: 404 Client Error: Not Found for url: https://raw.githubusercontent.com/COGS108/Group-SP26-010/refs/heads/main/data/00-raw/COGS108ChronotypeSurvey.csv?token=GHSAT0AAAAAAD2FFZXLFJUC4CDSALS25NOG2QFETTQ

### Dataset #1 

Instructions: 
1. Change the header from Dataset #1 to something more descriptive of the dataset
2. Write a few paragraphs about this dataset. Make sure to cover
   1. Describe the important metrics, what units they are in, and giv some sense of what they mean.  For example "Fasting blood glucose in units of mg glucose per deciliter of blood.  Normal values for healthy individuals range from 70 to 100 mg/dL.  Values 100-125 are prediabetic and values >125mg/dL indicate diabetes. Values <70 indicate hypoglycemia. Fasting idicates the patient hasn't eaten in the last 8 hours.  If blood glucose is >250 or <50 at any time (regardless of the time of last meal) the patient's life may be in immediate danger"
   2. If there are any major concerns with the dataset, describe them. For example "Dataset is composed of people who are serious enough about eating healthy that they voluntarily downloaded an app dedicated to tracking their eating patterns. This sample is likely biased because of that self-selection. These people own smartphones and may be healthier and may have more disposable income than the average person.  Those who voluntarily log conscientiously and for long amounts of time are also likely even more interested in health than those who download the app and only log a bit before getting tired of it"
3. Use the cell below to 
    1. load the dataset 
    2. make the dataset tidy or demonstrate that it was already tidy
    3. demonstrate the size of the dataset
    4. find out how much data is missing, where its missing, and if its missing at random or seems to have any systematic relationships in its missingness
    5. find and flag any outliers or suspicious entries
    6. clean the data or demonstrate that it was already clean.  You may choose how to deal with missingness (dropna of fillna... how='any' or 'all') and you should justify your choice in some way
    7. You will load raw data from `data/00-raw/`, you will (optionally) write intermediate stages of your work to `data/01-interim` and you will write the final fully wrangled version of your data to `data/02-processed`
4. Optionally you can also show some summary statistics for variables that you think are important to the project
5. Feel free to add more cells here if that's helpful for you

In [3]:
## YOUR CODE TO LOAD/CLEAN/TIDY/WRANGLE THE DATA GOES HERE
import pandas as pd
import numpy as np

#Load Raw Data Set
raw_file = pd.read_csv('data/00-raw/COGS108ChronotypeSurvey.csv')
raw_file.head()

# Tidy Data:
# The original data is already Tidy because each variable is its own column, each response forms a row, 
# and each cell is a single measurement.

,StartDate,EndDate,Status,IPAddress,Progress,Duration (in seconds),Finished,RecordedDate,ResponseId,RecipientLastName,...,Q10,Q12_1,Q13_1,Q11,Q20,Q21,Q15_1,Q16,Q17,Q19_1
0,Start Date,End Date,Response Type,IP Address,Progress,Duration (in seconds),Finished,Recorded Date,Response ID,Recipient Last Name,...,"On a day with no commitments, when would you n...","In the past week, how well-rested have you fel...",How consistent is your sleep quality week to w...,"On an average night, how many times do you wak...","On an average night, how many minutes does it ...","On an average night, how many minutes do you s...","In the past week, how many days have you consu...",What is your overall GPA?,What category does your major belong to?,How many hours per day do you typically spend ...
1,"{""ImportId"":""startDate"",""timeZone"":""America/De...","{""ImportId"":""endDate"",""timeZone"":""America/Denv...","{""ImportId"":""status""}","{""ImportId"":""ipAddress""}","{""ImportId"":""progress""}","{""ImportId"":""duration""}","{""ImportId"":""finished""}","{""ImportId"":""recordedDate"",""timeZone"":""America...","{""ImportId"":""_recordId""}","{""ImportId"":""recipientLastName""}",...,"{""ImportId"":""QID7_TEXT""}","{""ImportId"":""QID10_1""}","{""ImportId"":""QID12_1""}","{""ImportId"":""QID9""}","{""ImportId"":""QID22_TEXT""}","{""ImportId"":""QID23_TEXT""}","{""ImportId"":""QID21_1""}","{""ImportId"":""QID11_TEXT""}","{""ImportId"":""QID17""}","{""ImportId"":""QID19_1""}"
2,2026-05-09 17:26:29,2026-05-09 17:28:46,Survey Preview,NaN,100,137,True,2026-05-09 17:28:47,R_6liz3Fbi7IUv3oI,NaN,...,8,4,3,1-2 times,NaN,NaN,NaN,4.0,NaN,4
3,2026-05-11 09:36:53,2026-05-11 09:39:31,Survey Preview,NaN,100,158,True,2026-05-11 09:39:32,R_5dMXIPFBDzTtnKi,NaN,...,7.5,3,4,1-2 times,25,0,0,4.0,STEM,2
4,2026-05-11 09:41:57,2026-05-11 09:42:00,Survey Preview,NaN,100,2,True,2026-05-11 09:42:00,R_56i5etjobD9xzeS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
#Tidy Data
# replace the titles that qualtrics automatically generated

raw_file.columns = raw_file.iloc[0]
new_header = raw_file[2:].reset_index(drop=True)
new_header.head()

,Start Date,End Date,Response Type,IP Address,Progress,Duration (in seconds),Finished,Recorded Date,Response ID,Recipient Last Name,...,"On a day with no commitments, when would you naturally wake up?","In the past week, how well-rested have you felt upon waking up? - 0 = Not rested, 5 = Well rested","How consistent is your sleep quality week to week? - 0 = Not consistent, 5 = Consistent","On an average night, how many times do you wake up in the middle of the night?","On an average night, how many minutes does it take you to fall asleep?","On an average night, how many minutes do you spend on your phone directly before going to bed?","In the past week, how many days have you consumed caffeine six hours or less before going to bed? (e.g. consuming caffeine any time after 4PM if average bedtime is 10PM) - Days",What is your overall GPA?,What category does your major belong to?,How many hours per day do you typically spend doing extracurriculars during the week? - Hours per day
0,2026-05-09 17:26:29,2026-05-09 17:28:46,Survey Preview,NaN,100,137,True,2026-05-09 17:28:47,R_6liz3Fbi7IUv3oI,NaN,...,8,4,3,1-2 times,NaN,NaN,NaN,4.0,NaN,4
1,2026-05-11 09:36:53,2026-05-11 09:39:31,Survey Preview,NaN,100,158,True,2026-05-11 09:39:32,R_5dMXIPFBDzTtnKi,NaN,...,7.5,3,4,1-2 times,25,0,0,4.0,STEM,2
2,2026-05-11 09:41:57,2026-05-11 09:42:00,Survey Preview,NaN,100,2,True,2026-05-11 09:42:00,R_56i5etjobD9xzeS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2026-05-11 13:07:51,2026-05-11 13:09:27,Survey Preview,NaN,100,96,True,2026-05-11 13:09:27,R_6j1Y4aEpdBVg717,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2026-05-11 13:20:20,2026-05-11 13:21:16,Survey Preview,NaN,100,55,True,2026-05-11 13:21:16,R_5I3dY7Eaqjq9ffX,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
print(new_header.columns)

Index(['Start Date', 'End Date', 'Response Type', 'IP Address', 'Progress',
       'Duration (in seconds)', 'Finished', 'Recorded Date', 'Response ID',
       'Recipient Last Name', 'Recipient First Name', 'Recipient Email',
       'External Data Reference', 'Location Latitude', 'Location Longitude',
       'Distribution Channel', 'User Language',
       'Thank you for participating in this survey! \n\nResponses to this questionnaire will be used for a class project for COGS108: Intro to Data Science. This is an anonymous survey-- no personal identifiers will be recorded from your participation. \n\nBy clicking "Yes, I consent to my responses being used", you are consenting to the usage of your answers for data analysis.',
       'Have you ever been diagnosed with a sleep disorder?',
       'Are you 18 years or older and currently enrolled as an undergraduate student?',
       'What is your sex?', 'What is your age?',
       'In the past week, on a day with work or school, what is the average time you have gone to bed?',
       'In the past week, on a day with work or school, what is the average time you have woken up?',
       'On a day with no commitments, when would you naturally go to bed?',
       'On a day with no commitments, when would you naturally wake up?',
       'In the past week, how well-rested have you felt upon waking up? - 0 = Not rested,              5 = Well rested',
       'How consistent is your sleep quality week to week? - 0 = Not consistent,        5 = Consistent',
       'On an average night, how many times do you wake up in the middle of the night?',
       'On an average night, how many minutes does it take you to fall asleep?',
       'On an average night, how many minutes do you spend on your phone directly before going to bed?',
       'In the past week, how many days have you consumed caffeine six hours or less before going to bed? (e.g. consuming caffeine any time after 4PM if average bedtime is 10PM) - Days',
       'What is your overall GPA?', 'What category does your major belong to?',
       'How many hours per day do you typically spend doing extracurriculars during the week? - Hours per day'],
      dtype='object', name=0)

In [6]:
#Clean Data

#drops the data that qualtrics automatically generated with the survey as well as the answers with 'Nan' responses
#Using dropna() was also the best choice in case of our data because it ensures that only participants who provided 
#complete responses are included in your analysis. Because many of our variables like bedtime, wake time, sleep latency, 
#caffeine use, GPA, and extracurricular hours are  being compared against each other, missing values would make
#statistical analysis inconsistent and harder to interpret.
#These NA values appear to be random errors in participant responses or lack of full participation.

drop_unnecessary = new_header.drop(columns = 
                [ 'Start Date', 'End Date', 'Response Type', 'IP Address', 'Progress',
                  'Duration (in seconds)', 'Finished', 'Recorded Date',
                  'Recipient Last Name', 'Recipient First Name', 'Recipient Email',
                  'External Data Reference', 'Location Latitude', 'Location Longitude',
                  'Distribution Channel', 'User Language' ]).dropna()
drop_unnecessary

,Response ID,"Thank you for participating in this survey! \n\nResponses to this questionnaire will be used for a class project for COGS108: Intro to Data Science. This is an anonymous survey-- no personal identifiers will be recorded from your participation. \n\nBy clicking ""Yes, I consent to my responses being used"", you are consenting to the usage of your answers for data analysis.",Have you ever been diagnosed with a sleep disorder?,Are you 18 years or older and currently enrolled as an undergraduate student?,What is your sex?,What is your age?,"In the past week, on a day with work or school, what is the average time you have gone to bed?","In the past week, on a day with work or school, what is the average time you have woken up?","On a day with no commitments, when would you naturally go to bed?","On a day with no commitments, when would you naturally wake up?","In the past week, how well-rested have you felt upon waking up? - 0 = Not rested, 5 = Well rested","How consistent is your sleep quality week to week? - 0 = Not consistent, 5 = Consistent","On an average night, how many times do you wake up in the middle of the night?","On an average night, how many minutes does it take you to fall asleep?","On an average night, how many minutes do you spend on your phone directly before going to bed?","In the past week, how many days have you consumed caffeine six hours or less before going to bed? (e.g. consuming caffeine any time after 4PM if average bedtime is 10PM) - Days",What is your overall GPA?,What category does your major belong to?,How many hours per day do you typically spend doing extracurriculars during the week? - Hours per day
1,R_5dMXIPFBDzTtnKi,"Yes, I consent to my responses being used","No, I have not been diagnosed with a sleep dis...","Yes, I am 18 years or older and currently enro...",Male,20,22.5,6.5,11,7.5,3,4,1-2 times,25,0,0,4.0,STEM,2
5,R_5SdbL9YAUtzdtxl,"Yes, I consent to my responses being used","No, I have not been diagnosed with a sleep dis...","Yes, I am 18 years or older and currently enro...",Female,19,2,11,4,13,2,1,3-4 times,60,12,7,3,STEM,11
6,R_1MfeBnHIGr4YdIR,"Yes, I consent to my responses being used","No, I have not been diagnosed with a sleep dis...","Yes, I am 18 years or older and currently enro...",Male,25,11,8,1,9,2,4,1-2 times,25,60,0,3.8,Social Sciences,3
7,R_1gMKnWRUSyj4n5E,"Yes, I consent to my responses being used","No, I have not been diagnosed with a sleep dis...","Yes, I am 18 years or older and currently enro...",Female,21,12,8,12,10,3,2,3-4 times,40,10,3,3.7,Health & Medicine,16
10,R_7vTHj6lSttZOu9b,"Yes, I consent to my responses being used","No, I have not been diagnosed with a sleep dis...","Yes, I am 18 years or older and currently enro...",Female,24,3,12,1,12,5,4,1-2 times,30,90,0,2.00,STEM,4
12,R_5bZB4WWLgYgJHS5,"Yes, I consent to my responses being used","No, I have not been diagnosed with a sleep dis...","Yes, I am 18 years or older and currently enro...",Female,21,23,9,23,9.5,1,2,1-2 times,10,15,0,3.97,Social Sciences,5
17,R_1rZLQqphNO2bwFP,"Yes, I consent to my responses being used","No, I have not been diagnosed with a sleep dis...","Yes, I am 18 years or older and currently enro...",Male,19,2,10,2,15,2,3,1-2 times,15,60,4,2.7,Social Sciences,3
18,R_1GR57xbIA2k6L8l,"Yes, I consent to my responses being used","No, I have not been diagnosed with a sleep dis...","Yes, I am 18 years or older and currently enro...",Female,21,10,6,10,8,4,4,1-2 times,10,15,1,3.91,Social Sciences,19
21,R_12rptBBD0dsKkQI,"Yes, I consent to my responses being used","No, I have not been diagnosed with a sleep dis...","Yes, I am 18 years or older and currently enro...",Male,23,2,7,12,11,2,2,0 times,35,20,1,3.8,Social Sciences,2
22,R_5Oho93UkPjJQI9z,"Yes, I consent to my responses being used","No, I have not been diagnosed with a sleep dis...","Yes, I am 18 years or older and currently enro...",Female,21,6,10,6,12,3,1,0 times,5,25,1,3.6,Social Sciences,6
25,R_1JRqUH0wqI2lTSm,"Yes, I consent to my responses being used","No, I have not been diagnosed with a sleep dis...","Yes, I am 18 years or older and currently enro...",Female,20,22,6,23,9,3,4,1-2 times,30,30,2,3.97,Social Sciences,4
27,R_5fGBkYNdWWeOK5k,"Yes, I consent to my responses being used","No, I have not been diagnosed with a sleep dis...","Yes, I am 18 years or older and currently enro...",Female,19,23,8,22,10,3,4,1-2 times,10,10,1,3.96,Social Sciences,2
29,R_6DU9lt5W2g6XFOh,"Yes, I consent to my responses being used","No, I have not been diagnosed with a sleep dis...","Yes, I am 18 years or older and currently enro...",Female,19,1,10,24,10,2,2,0 times,20,20,1,3.4,Social Sciences,4
30,R_7rTagcUUGQpRJru,"Yes, I consent to my responses being used","No, I have not been diagnosed with a sleep dis...","Yes, I am 18 years or older and currently enro...",Female,20,24,8,1,10,2,3,3-4 times,20,30,1,3.5,STEM,1
31,R_1Hi7k1sBZEusSod,"Yes, I consent to my responses being used","No, I have not been diagnosed with a sleep dis...","Yes, I am 18 years or older and currently enro...",Female,22,3,9,3,13,1,5,0 times,5,15,0,3.71,Social Sciences,0
32,R_77seAOFp41eJrEu,"Yes, I consent to my responses being used","No, I have not been diagnosed with a sleep dis...","Yes, I am 18 years or older and currently enro...",Female,19,1,9,1,10,3,3,3-4 times,45,60,3,3.4,STEM,2
33,R_63jbHQnzkidRldw,"Yes, I consent to my responses being used","No, I have not been diagnosed with a sleep dis...","Yes, I am 18 years or older and currently enro...",Male,20,24,8,23,8,3,3,0 times,10,20,1,3.8,Business & Economics,6
34,R_74ARxoEs1QpFCzh,"Yes, I consent to my responses being used","No, I have not been diagnosed with a sleep dis...","Yes, I am 18 years or older and currently enro...",Female,19,10,8,9,9,1,1,1-2 times,30,30,1,3.0,STEM,4
37,R_62ByOt3ajSAL8rv,"Yes, I consent to my responses being used","No, I have not been diagnosed with a sleep dis...","Yes, I am 18 years or older and currently enro...",Male,20,11,7,12,8,3,2,0 times,10,10,6,3.6,STEM,5
38,R_5QPz99IqbJztNdj,"Yes, I consent to my responses being used","No, I have not been diagnosed with a sleep dis...","Yes, I am 18 years or older and currently enro...",Male,20,22,5,22,5,5,5,1-2 times,5,0,0,3.9,STEM,3
39,R_6ccpyf0AnusTaCJ,"Yes, I consent to my responses being used","No, I have not been diagnosed with a sleep dis...","Yes, I am 18 years or older and currently enro...",Male,19,1,10,23,10,3,4,0 times,5,15,0,3.6,Business & Economics,11
40,R_6G9UqA4ZsX6OLL4,"Yes, I consent to my responses being used","No, I have not been diagnosed with a sleep dis...","Yes, I am 18 years or older and currently enro...",Female,19,23,9,24,10,2,3,1-2 times,15,30,0,4.0,STEM,10
41,R_3jPF7Bm7ulxmVot,"Yes, I consent to my responses being used","No, I have not been diagnosed with a sleep dis...","Yes, I am 18 years or older and currently enro...",Male,19,1,9,1,10,3,4,0 times,10,15,0,3.83,STEM,4
43,R_6A4Pe8uCsbiHJTz,"Yes, I consent to my responses being used","No, I have not been diagnosed with a sleep dis...","Yes, I am 18 years or older and currently enro...",Female,19,1,7,12,7,5,5,0 times,10,75,3,3.1,Arts & Humanities,6
45,R_1UWb9T54ysgbrK4,"Yes, I consent to my responses being used","No, I have not been diagnosed with a sleep dis...","Yes, I am 18 years or older and currently enro...",Male,20,23,9,22,6,3,4,0 times,10,0,0,3.94,Social Sciences,2
47,R_3YCYBINKPMRIRLA,"Yes, I consent to my responses being used","No, I have not been diagnosed with a sleep dis...","Yes, I am 18 years or older and currently enro...",Female,21,23,7,22,10,2,2,0 times,15,30,0,3.0,Social Sciences,6
50,R_5KoHn2oztnt54bH,"Yes, I consent to my responses being used","No, I have not been diagnosed with a sleep dis...","Yes, I am 18 years or older and currently enro...",Female,20,1,8,2,11,3,2,1-2 times,60,30,3,3.6,STEM,15
51,R_5ADAVOJkKmmAvS1,"Yes, I consent to my responses being used","No, I have not been diagnosed with a sleep dis...","Yes, I am 18 years or older and currently enro...",Male,20,20,4,24,10,3,4,1-2 times,10,15,5,3.71,Business & Economics,15
52,R_1jcb6kl62phLHHK,"Yes, I consent to my responses being used","No, I have not been diagnosed with a sleep dis...","Yes, I am 18 years or older and currently enro...",Female,20,12,10,12,11,3,3,3-4 times,30,40,3,3.8,Other,6
55,R_1KI5dnk2xYrKzFs,"Yes, I consent to my responses being used","No, I have not been diagnosed with a sleep dis...","Yes, I am 18 years or older and currently enro...",Male,19,24,9,1,10,1,3,0 times,20,40,0,3.87,Business & Economics,15
60,R_1mqhrsbTvf4tnaU,"Yes, I consent to my responses being used","No, I have not been diagnosed with a sleep dis...","Yes, I am 18 years or older and currently enro...",Female,18,23,10,2,10,2,2,0 times,15,100,2,3,Business & Economics,3
62,R_3pQCseL783sYvmG,"Yes, I consent to my responses being used","No, I have not been diagnosed with a sleep dis...","Yes, I am 18 years or older and currently enro...",Male,20,10,7,11,7,4,4,1-2 times,20,0,0,3.5,Business & Economics,10
64,R_7RPW3nRXQ7ruap9,"Yes, I consent to my responses being used","No, I have not been diagnosed with a sleep dis...","Yes, I am 18 years or older and currently enro...",Male,23,24,8,24,9,2,2,0 times,20,60,0,3.6,Social Sciences,0
66,R_3y4lxfMShI5imLH,"Yes, I consent to my responses being used","No, I have not been diagnosed with a sleep dis...","Yes, I am 18 years or older and currently enro...",Female,20,22,8,22,10,3,3,1-2 times,30,60,4,3.8,Other,3

In [7]:
#Clean Data

#Renames the columns for better readability and removes columns only useful for participant screening. Shows the shape of the dataframe after removing NAs and irrelevant columns
#Note that all data is measure in the Past week and all Scales are weighed from 0-5 with 0 being not
#rested and 5 being well rested (Rested Score, and Sleep Consistency)

rename_columns = drop_unnecessary.rename(columns=
               {
                 drop_unnecessary.columns[1]: 'consent',
                 drop_unnecessary.columns[2]: 'sleep_disorder',
                 drop_unnecessary.columns[3]: 'eligible_undergrad',
                 drop_unnecessary.columns[4]: 'sex',
                 drop_unnecessary.columns[5]: 'age',
                 drop_unnecessary.columns[6]: 'weekday_bedtime',
                 drop_unnecessary.columns[7]: 'weekday_wakeup',
                 drop_unnecessary.columns[8]: 'free_day_bedtime',
                 drop_unnecessary.columns[9]: 'free_day_wakeup',
                 drop_unnecessary.columns[10]: 'well_rested',
                 drop_unnecessary.columns[11]: 'sleep_consistency',
                 drop_unnecessary.columns[12]: 'night_wake_frequency',
                 drop_unnecessary.columns[13]: 'sleep_latency_minutes',
                 drop_unnecessary.columns[14]: 'pre_bed_phone_minutes',
                 drop_unnecessary.columns[15]: 'late_caffeine_days',
                 drop_unnecessary.columns[16]: 'gpa',
                 drop_unnecessary.columns[17]: 'major_category',
                 drop_unnecessary.columns[18]: 'extracurricular_hours_per_day',                                                       
                                                                        })
rename_columns = rename_columns.drop(columns = ['consent','sleep_disorder','eligible_undergrad'])

print(rename_columns.shape)
rename_columns.head()

(34, 16)

,Response ID,sex,age,weekday_bedtime,weekday_wakeup,free_day_bedtime,free_day_wakeup,well_rested,sleep_consistency,night_wake_frequency,sleep_latency_minutes,pre_bed_phone_minutes,late_caffeine_days,gpa,major_category,extracurricular_hours_per_day
1,R_5dMXIPFBDzTtnKi,Male,20,22.5,6.5,11,7.5,3,4,1-2 times,25,0,0,4.0,STEM,2
5,R_5SdbL9YAUtzdtxl,Female,19,2,11,4,13,2,1,3-4 times,60,12,7,3,STEM,11
6,R_1MfeBnHIGr4YdIR,Male,25,11,8,1,9,2,4,1-2 times,25,60,0,3.8,Social Sciences,3
7,R_1gMKnWRUSyj4n5E,Female,21,12,8,12,10,3,2,3-4 times,40,10,3,3.7,Health & Medicine,16
10,R_7vTHj6lSttZOu9b,Female,24,3,12,1,12,5,4,1-2 times,30,90,0,2.00,STEM,4

In [8]:
#Clean Data

#Sets Index to be responder Id so that it is unique for each responder. 

unique_index = rename_columns.iloc[1:].reset_index(drop=True)
unique_index = unique_index.set_index("Response ID")
unique_index.head()

,sex,age,weekday_bedtime,weekday_wakeup,free_day_bedtime,free_day_wakeup,well_rested,sleep_consistency,night_wake_frequency,sleep_latency_minutes,pre_bed_phone_minutes,late_caffeine_days,gpa,major_category,extracurricular_hours_per_day
Response ID,,,,,,,,,,,,,,,
R_5SdbL9YAUtzdtxl,Female,19,2,11,4,13,2,1,3-4 times,60,12,7,3,STEM,11
R_1MfeBnHIGr4YdIR,Male,25,11,8,1,9,2,4,1-2 times,25,60,0,3.8,Social Sciences,3
R_1gMKnWRUSyj4n5E,Female,21,12,8,12,10,3,2,3-4 times,40,10,3,3.7,Health & Medicine,16
R_7vTHj6lSttZOu9b,Female,24,3,12,1,12,5,4,1-2 times,30,90,0,2.00,STEM,4
R_5bZB4WWLgYgJHS5,Female,21,23,9,23,9.5,1,2,1-2 times,10,15,0,3.97,Social Sciences,5

In [9]:
#Converts Numeric data to numeric data type

numeric_cols = [
    'age',
    'weekday_bedtime',
    'free_day_bedtime',
    'weekday_wakeup',
    'free_day_wakeup',
    'sleep_latency_minutes',
    'pre_bed_phone_minutes',
    'well_rested',
    'sleep_consistency',
    'late_caffeine_days',
    'gpa',
    'extracurricular_hours_per_day'
]

clean_num_cat = unique_index.copy()
clean_num_cat[numeric_cols] = clean_num_cat[numeric_cols].apply(pd.to_numeric,errors='coerce')

clean_num_cat.head()

,sex,age,weekday_bedtime,weekday_wakeup,free_day_bedtime,free_day_wakeup,well_rested,sleep_consistency,night_wake_frequency,sleep_latency_minutes,pre_bed_phone_minutes,late_caffeine_days,gpa,major_category,extracurricular_hours_per_day
Response ID,,,,,,,,,,,,,,,
R_5SdbL9YAUtzdtxl,Female,19,2,11,4,13.0,2,1,3-4 times,60,12,7,3.00,STEM,11
R_1MfeBnHIGr4YdIR,Male,25,11,8,1,9.0,2,4,1-2 times,25,60,0,3.80,Social Sciences,3
R_1gMKnWRUSyj4n5E,Female,21,12,8,12,10.0,3,2,3-4 times,40,10,3,3.70,Health & Medicine,16
R_7vTHj6lSttZOu9b,Female,24,3,12,1,12.0,5,4,1-2 times,30,90,0,2.00,STEM,4
R_5bZB4WWLgYgJHS5,Female,21,23,9,23,9.5,1,2,1-2 times,10,15,0,3.97,Social Sciences,5

In [10]:
#Clean Data
# Checks that GPA <= 4.0, and there is no negative sleep latency and removes data that doesn't fall within the boundary

real_values = clean_num_cat[
    (clean_num_cat['gpa'].between(0, 4.0)) &
    (clean_num_cat['sleep_latency_minutes'] >= 0) 
]
real_values

,sex,age,weekday_bedtime,weekday_wakeup,free_day_bedtime,free_day_wakeup,well_rested,sleep_consistency,night_wake_frequency,sleep_latency_minutes,pre_bed_phone_minutes,late_caffeine_days,gpa,major_category,extracurricular_hours_per_day
Response ID,,,,,,,,,,,,,,,
R_5SdbL9YAUtzdtxl,Female,19,2,11,4,13.0,2,1,3-4 times,60,12,7,3.00,STEM,11
R_1MfeBnHIGr4YdIR,Male,25,11,8,1,9.0,2,4,1-2 times,25,60,0,3.80,Social Sciences,3
R_1gMKnWRUSyj4n5E,Female,21,12,8,12,10.0,3,2,3-4 times,40,10,3,3.70,Health & Medicine,16
R_7vTHj6lSttZOu9b,Female,24,3,12,1,12.0,5,4,1-2 times,30,90,0,2.00,STEM,4
R_5bZB4WWLgYgJHS5,Female,21,23,9,23,9.5,1,2,1-2 times,10,15,0,3.97,Social Sciences,5
R_1rZLQqphNO2bwFP,Male,19,2,10,2,15.0,2,3,1-2 times,15,60,4,2.70,Social Sciences,3
R_1GR57xbIA2k6L8l,Female,21,10,6,10,8.0,4,4,1-2 times,10,15,1,3.91,Social Sciences,19
R_12rptBBD0dsKkQI,Male,23,2,7,12,11.0,2,2,0 times,35,20,1,3.80,Social Sciences,2
R_5Oho93UkPjJQI9z,Female,21,6,10,6,12.0,3,1,0 times,5,25,1,3.60,Social Sciences,6
R_1JRqUH0wqI2lTSm,Female,20,22,6,23,9.0,3,4,1-2 times,30,30,2,3.97,Social Sciences,4
R_5fGBkYNdWWeOK5k,Female,19,23,8,22,10.0,3,4,1-2 times,10,10,1,3.96,Social Sciences,2
R_6DU9lt5W2g6XFOh,Female,19,1,10,24,10.0,2,2,0 times,20,20,1,3.40,Social Sciences,4
R_7rTagcUUGQpRJru,Female,20,24,8,1,10.0,2,3,3-4 times,20,30,1,3.50,STEM,1
R_1Hi7k1sBZEusSod,Female,22,3,9,3,13.0,1,5,0 times,5,15,0,3.71,Social Sciences,0
R_77seAOFp41eJrEu,Female,19,1,9,1,10.0,3,3,3-4 times,45,60,3,3.40,STEM,2
R_63jbHQnzkidRldw,Male,20,24,8,23,8.0,3,3,0 times,10,20,1,3.80,Business & Economics,6
R_74ARxoEs1QpFCzh,Female,19,10,8,9,9.0,1,1,1-2 times,30,30,1,3.00,STEM,4
R_62ByOt3ajSAL8rv,Male,20,11,7,12,8.0,3,2,0 times,10,10,6,3.60,STEM,5
R_5QPz99IqbJztNdj,Male,20,22,5,22,5.0,5,5,1-2 times,5,0,0,3.90,STEM,3
R_6ccpyf0AnusTaCJ,Male,19,1,10,23,10.0,3,4,0 times,5,15,0,3.60,Business & Economics,11
R_6G9UqA4ZsX6OLL4,Female,19,23,9,24,10.0,2,3,1-2 times,15,30,0,4.00,STEM,10
R_3jPF7Bm7ulxmVot,Male,19,1,9,1,10.0,3,4,0 times,10,15,0,3.83,STEM,4
R_6A4Pe8uCsbiHJTz,Female,19,1,7,12,7.0,5,5,0 times,10,75,3,3.10,Arts & Humanities,6
R_1UWb9T54ysgbrK4,Male,20,23,9,22,6.0,3,4,0 times,10,0,0,3.94,Social Sciences,2
R_3YCYBINKPMRIRLA,Female,21,23,7,22,10.0,2,2,0 times,15,30,0,3.00,Social Sciences,6
R_5KoHn2oztnt54bH,Female,20,1,8,2,11.0,3,2,1-2 times,60,30,3,3.60,STEM,15
R_5ADAVOJkKmmAvS1,Male,20,20,4,24,10.0,3,4,1-2 times,10,15,5,3.71,Business & Economics,15
R_1jcb6kl62phLHHK,Female,20,12,10,12,11.0,3,3,3-4 times,30,40,3,3.80,Other,6
R_1KI5dnk2xYrKzFs,Male,19,24,9,1,10.0,1,3,0 times,20,40,0,3.87,Business & Economics,15
R_1mqhrsbTvf4tnaU,Female,18,23,10,2,10.0,2,2,0 times,15,100,2,3.00,Business & Economics,3
R_3pQCseL783sYvmG,Male,20,10,7,11,7.0,4,4,1-2 times,20,0,0,3.50,Business & Economics,10
R_7RPW3nRXQ7ruap9,Male,23,24,8,24,9.0,2,2,0 times,20,60,0,3.60,Social Sciences,0
R_3y4lxfMShI5imLH,Female,20,22,8,22,10.0,3,3,1-2 times,30,60,4,3.80,Other,3

In [11]:
#We asked participants to report their sleep and wake times as 24hr time scale numbers, but only some complied
#This code checks if a participants bedtime is reported as 8am-12pm (really strange) and checks that they don't use 24hr scale for the wake time
#for datapoints that pass this check, 12 is added to their value to correct them

error1 = (
    real_values['weekday_bedtime'].between(8,12) &
    ~real_values['weekday_wakeup'].between(13,24)
)
error2 = (
    real_values['free_day_bedtime'].between(8,12) &
    ~real_values['free_day_wakeup'].between(13,24)
)

corrected_values = real_values.copy()

corrected_values.loc[error1, 'weekday_bedtime'] += 12
corrected_values.loc[error2, 'free_day_bedtime'] += 12

corrected_values.head()

,sex,age,weekday_bedtime,weekday_wakeup,free_day_bedtime,free_day_wakeup,well_rested,sleep_consistency,night_wake_frequency,sleep_latency_minutes,pre_bed_phone_minutes,late_caffeine_days,gpa,major_category,extracurricular_hours_per_day
Response ID,,,,,,,,,,,,,,,
R_5SdbL9YAUtzdtxl,Female,19,2,11,4,13.0,2,1,3-4 times,60,12,7,3.00,STEM,11
R_1MfeBnHIGr4YdIR,Male,25,23,8,1,9.0,2,4,1-2 times,25,60,0,3.80,Social Sciences,3
R_1gMKnWRUSyj4n5E,Female,21,24,8,24,10.0,3,2,3-4 times,40,10,3,3.70,Health & Medicine,16
R_7vTHj6lSttZOu9b,Female,24,3,12,1,12.0,5,4,1-2 times,30,90,0,2.00,STEM,4
R_5bZB4WWLgYgJHS5,Female,21,23,9,23,9.5,1,2,1-2 times,10,15,0,3.97,Social Sciences,5

In [12]:
#From the clean data we can now calculate chronotype through sleep midpoint, sleep duration, and chronotype mismatch between midpoints


corrected_values['weekday_sleep_duration'] = (
    corrected_values['weekday_wakeup'] -
    corrected_values['weekday_bedtime']) % 24

corrected_values['free_day_sleep_duration'] = (
    corrected_values['free_day_wakeup'] -
    corrected_values['free_day_bedtime']) % 24

corrected_values['weekday_sleep_midpoint'] = (
    corrected_values['weekday_bedtime'] +
    corrected_values['weekday_sleep_duration'] / 2) % 24

corrected_values['free_day_sleep_midpoint'] = (
    corrected_values['free_day_bedtime'] +
    corrected_values['free_day_sleep_duration'] / 2) % 24

corrected_values['chronotype_mismatch'] = (
    corrected_values['free_day_sleep_midpoint'] -
    corrected_values['weekday_sleep_midpoint']).abs()

full_values = corrected_values.copy()
full_values

,sex,age,weekday_bedtime,weekday_wakeup,free_day_bedtime,free_day_wakeup,well_rested,sleep_consistency,night_wake_frequency,sleep_latency_minutes,pre_bed_phone_minutes,late_caffeine_days,gpa,major_category,extracurricular_hours_per_day,weekday_sleep_duration,free_day_sleep_duration,weekday_sleep_midpoint,free_day_sleep_midpoint,chronotype_mismatch
Response ID,,,,,,,,,,,,,,,,,,,,
R_5SdbL9YAUtzdtxl,Female,19,2,11,4,13.0,2,1,3-4 times,60,12,7,3.00,STEM,11,9,9.0,6.5,8.50,2.00
R_1MfeBnHIGr4YdIR,Male,25,23,8,1,9.0,2,4,1-2 times,25,60,0,3.80,Social Sciences,3,9,8.0,3.5,5.00,1.50
R_1gMKnWRUSyj4n5E,Female,21,24,8,24,10.0,3,2,3-4 times,40,10,3,3.70,Health & Medicine,16,8,10.0,4.0,5.00,1.00
R_7vTHj6lSttZOu9b,Female,24,3,12,1,12.0,5,4,1-2 times,30,90,0,2.00,STEM,4,9,11.0,7.5,6.50,1.00
R_5bZB4WWLgYgJHS5,Female,21,23,9,23,9.5,1,2,1-2 times,10,15,0,3.97,Social Sciences,5,10,10.5,4.0,4.25,0.25
R_1rZLQqphNO2bwFP,Male,19,2,10,2,15.0,2,3,1-2 times,15,60,4,2.70,Social Sciences,3,8,13.0,6.0,8.50,2.50
R_1GR57xbIA2k6L8l,Female,21,22,6,22,8.0,4,4,1-2 times,10,15,1,3.91,Social Sciences,19,8,10.0,2.0,3.00,1.00
R_12rptBBD0dsKkQI,Male,23,2,7,24,11.0,2,2,0 times,35,20,1,3.80,Social Sciences,2,5,11.0,4.5,5.50,1.00
R_5Oho93UkPjJQI9z,Female,21,6,10,6,12.0,3,1,0 times,5,25,1,3.60,Social Sciences,6,4,6.0,8.0,9.00,1.00
R_1JRqUH0wqI2lTSm,Female,20,22,6,23,9.0,3,4,1-2 times,30,30,2,3.97,Social Sciences,4,8,10.0,2.0,4.00,2.00
R_5fGBkYNdWWeOK5k,Female,19,23,8,22,10.0,3,4,1-2 times,10,10,1,3.96,Social Sciences,2,9,12.0,3.5,4.00,0.50
R_6DU9lt5W2g6XFOh,Female,19,1,10,24,10.0,2,2,0 times,20,20,1,3.40,Social Sciences,4,9,10.0,5.5,5.00,0.50
R_7rTagcUUGQpRJru,Female,20,24,8,1,10.0,2,3,3-4 times,20,30,1,3.50,STEM,1,8,9.0,4.0,5.50,1.50
R_1Hi7k1sBZEusSod,Female,22,3,9,3,13.0,1,5,0 times,5,15,0,3.71,Social Sciences,0,6,10.0,6.0,8.00,2.00
R_77seAOFp41eJrEu,Female,19,1,9,1,10.0,3,3,3-4 times,45,60,3,3.40,STEM,2,8,9.0,5.0,5.50,0.50
R_63jbHQnzkidRldw,Male,20,24,8,23,8.0,3,3,0 times,10,20,1,3.80,Business & Economics,6,8,9.0,4.0,3.50,0.50
R_74ARxoEs1QpFCzh,Female,19,22,8,21,9.0,1,1,1-2 times,30,30,1,3.00,STEM,4,10,12.0,3.0,3.00,0.00
R_62ByOt3ajSAL8rv,Male,20,23,7,24,8.0,3,2,0 times,10,10,6,3.60,STEM,5,8,8.0,3.0,4.00,1.00
R_5QPz99IqbJztNdj,Male,20,22,5,22,5.0,5,5,1-2 times,5,0,0,3.90,STEM,3,7,7.0,1.5,1.50,0.00
R_6ccpyf0AnusTaCJ,Male,19,1,10,23,10.0,3,4,0 times,5,15,0,3.60,Business & Economics,11,9,11.0,5.5,4.50,1.00
R_6G9UqA4ZsX6OLL4,Female,19,23,9,24,10.0,2,3,1-2 times,15,30,0,4.00,STEM,10,10,10.0,4.0,5.00,1.00
R_3jPF7Bm7ulxmVot,Male,19,1,9,1,10.0,3,4,0 times,10,15,0,3.83,STEM,4,8,9.0,5.0,5.50,0.50
R_6A4Pe8uCsbiHJTz,Female,19,1,7,24,7.0,5,5,0 times,10,75,3,3.10,Arts & Humanities,6,6,7.0,4.0,3.50,0.50
R_1UWb9T54ysgbrK4,Male,20,23,9,22,6.0,3,4,0 times,10,0,0,3.94,Social Sciences,2,10,8.0,4.0,2.00,2.00
R_3YCYBINKPMRIRLA,Female,21,23,7,22,10.0,2,2,0 times,15,30,0,3.00,Social Sciences,6,8,12.0,3.0,4.00,1.00
R_5KoHn2oztnt54bH,Female,20,1,8,2,11.0,3,2,1-2 times,60,30,3,3.60,STEM,15,7,9.0,4.5,6.50,2.00
R_5ADAVOJkKmmAvS1,Male,20,20,4,24,10.0,3,4,1-2 times,10,15,5,3.71,Business & Economics,15,8,10.0,0.0,5.00,5.00
R_1jcb6kl62phLHHK,Female,20,24,10,24,11.0,3,3,3-4 times,30,40,3,3.80,Other,6,10,11.0,5.0,5.50,0.50
R_1KI5dnk2xYrKzFs,Male,19,24,9,1,10.0,1,3,0 times,20,40,0,3.87,Business & Economics,15,9,9.0,4.5,5.50,1.00
R_1mqhrsbTvf4tnaU,Female,18,23,10,2,10.0,2,2,0 times,15,100,2,3.00,Business & Economics,3,11,8.0,4.5,6.00,1.50
R_3pQCseL783sYvmG,Male,20,22,7,23,7.0,4,4,1-2 times,20,0,0,3.50,Business & Economics,10,9,8.0,2.5,3.00,0.50
R_7RPW3nRXQ7ruap9,Male,23,24,8,24,9.0,2,2,0 times,20,60,0,3.60,Social Sciences,0,8,9.0,4.0,4.50,0.50
R_3y4lxfMShI5imLH,Female,20,22,8,22,10.0,3,3,1-2 times,30,60,4,3.80,Other,3,10,12.0,3.0,4.00,1.00

In [16]:
#Checking the final df shape and saving file to repo

print(full_values.shape)
full_values.to_csv(
    'data/02-processed/full_values.csv',
    index=False)

import os
os.listdir('data/02-processed')

(33, 20)

['.gitkeep', 'full_values.csv']

## Ethics

A. Data Collection

A.1 Informed consent: If there are human subjects, have they given informed consent, where subjects affirmatively opt-in and have a clear understanding of the data used to which they consent?
Yes, we have human subjects. On the qualtrics survey platform for the data collection, the topic of our project was clearly stated and we provided a required question for them to answer regarding their consent to participate in our study. 

A.2 Collection bias: Have we considered sources of bias that could be introduced during data collection and survey design and taken steps to mitigate those? 
Yes, we have considered sources of bias related to the self- reporting aspect of our data collection .To help minimize framing effects and response bias, we used neutral wording throughout the questionnaire and designed questions to avoid leading participants towards specific answers. 

A.3 Limit PII exposure: Have we considered ways to minimize exposure of personally identifiable information (PII) for example through anonymization or not collecting information that isn't relevant for analysis?
In order to limit exposure of personally identifiable information, during our data collection we disclosed that the survey needed to be completed anonymously and we ensured that participants were asked questions relating to our study and were not prompted to release any of their personal identifiable information to us. 

A.4 Downstream bias mitigation: Have we considered ways to enable testing downstream results for biased outcomes (e.g., collecting data on protected group status like race or gender)?
While our study minimizes the collection of sensitive demographic information, limited demographic variables such as age and sex are collected to help assess potential subgroup differences and improve interpretability of findings.  

B. Data Storage

B.1 Data security: Do we have a plan to protect and secure data (e.g., encryption at rest and in transit, access controls on internal users and third parties, access logs, and up-to-date software)?
In order to protect and secure our data, we’ve limited the access control of our qualtrics survey (data collection site) so that the information submitted can only be accessed by our group members. 

B.2 Right to be forgotten: Do we have a mechanism through which an individual can request their personal information be removed?
Yes. At the beginning of our qualtrics survey we informed our participants that if they ever feel as though they wanted to withdraw from our study, they could come back in at any time and change their consent on the form. To ensure this is possible, we’ve left the qualtrics survey open for participants to be able to edit their responses. 

B.3 Data retention plan: Is there a schedule or plan to delete the data after it is no longer needed?
Yes. We plan to review our collected data at least once every three days and if we receive data that is not viable to us, we plan on deleting it from the secure exported survey datasets where the responses from our data collection site is populated in real time.  

C. Analysis
C.1 Missing perspectives: Have we sought to address blind spots in the analysis through engagement with relevant stakeholders (e.g., checking assumptions and discussing implications with affected communities and subject matter experts)?
To address potential blind spots with our collected information, we included an open-ended question that allows our participants to identify any factors we may have missed that affect their sleep and academic performance. We did this as a form of stakeholder engagement to make sure that the survey reflects the participants' lived experience and that any constraints we may not have anticipated in our original data collection will be collected.  

C.2 Dataset bias: Have we examined the data for possible sources of bias and taken steps to mitigate or address these biases (e.g., stereotype perpetuation, confirmation bias, imbalanced classes, or omitted confounding variables)?
We examined our dataset for potential sources of self- report and variable bias. Because sleep behavior and academic performance can be influenced by many external factors, we recognize that participants’ responses may be affected by lifestyle habits, extracurricular commitments, stress levels, and other unmeasured personal factors. To reduce reliance on a single subjective measure, we included multiple indicators of sleep behavior such as sleep duration, sleep timing, sleep consistency, nighttime awakenings, sleep latency, phone usage before sleep, and caffeine consumption before bed. We also acknowledge that the use of voluntary survey participation among undergraduate students may introduce sampling bias and limit generalizability of the findings to broader student populations. Additionally, limitations such as self- reported GPA and unmeasured factors including mental health and socioeconomic status may still influence the results of our analysis. 

C.3 Honest representation: Are our visualizations, summary statistics, and reports designed to honestly represent the underlying data?
Yes. We will ensure that our data is represented honestly by aligning all of our visualizations and summary statistics with the actual structure and limitation of our dataset. We will report both central tendencies and variability instead of single point summaries that may differ vastly across participants. In order to avoid overgeneralizing the relationship between sleep variables and GPA, we will report the relationship as correlation rather than causation. Our visualizations will also be representative of potential skews or subgroups in our data rather than a compressed visualization of the data averages.

C.4 Privacy in analysis: Have we ensured that data with PII are not used or displayed unless necessary for the analysis?
Yes. In our data collection we made sure to exclude any question requiring participants to provide us with PII so they will not be displayed or used in our project.

C.5 Auditability: Is the process of generating the analysis well documented and reproducible if we discover issues in the future?
Our process of generating analysis will be clearly documented and reproducible. To ensure this, we will be maintaining a consistent record of how our survey responses are cleaned, coded and transformed into variables we can analyze. All of our variables are also defined very clearly so that results can be replicated if needed. Our analysis workflow is also structured so that our data processing steps and our statistical procedures can be retraced and replicated if we discover any issues in the future.  

D. Modeling
D.1 Proxy discrimination: Have we ensured that the model does not rely on variables or proxies for variables that are unfairly discriminatory 
We made sure none of the variables in our model might serve as stand-ins for sensitive or protected traits. Rather than being demographic indicators, our predictors sleep length, chronotype mismatch, sleep timing, and academic variables are closely linked to behavioral and academic aspects. We do admit, though, that there may be an indirect correlation between socioeconomic position and some characteristics, such as major type or extracurricular workload. We take care where interpreting the data and refrain from drawing conclusions regarding innate group differences.  

D.2 Fairness across groups: Have we tested model results for fairness with respect to different affected groups (e.g., tested for disparate error rates)?
We evaluate fairness by examining whether model performance differs across accessible subgroups such as major category and sex. To identify any systemic differences, we analyze model fit and error trends across these groups. We recognize that a complete fairness evaluation is constrained by the limited demographic variables collected in our dataset. 

D.3 Metric selection: Have we considered the effects of optimizing for our defined metrics and considered additional metrics?
We use a variety of measures to analyze the effectiveness of the model, such as regression coefficients to look at the direction and strength of correlations and R2 to evaluate overall explanatory power.  To prevent becoming overly dependent on a single indicator, we also take statistical significance and effect size into account. This makes it possible to comprehend the relationship between sleep factors and GPA more thoroughly. 

D.4 Explainability: Can we explain in understandable terms a decision the model made in cases where a justification is needed?
Our model is naturally interpretable because multiple regression is being used. When all other factors are held constant, each coefficient shows the anticipated change GPA linked to a one- unit change in a predictor. This enables us to provide an easy-to-understand explanation of how variables like sleep length or chronotype mismatch affect academic achievement. 

D.5 Communicate limitations: Have we communicated the shortcomings, limitations, and biases of the model to relevant stakeholders in ways that can be generally understood?
We make it very apparent that our model cannot prove causality because it is based on observational, self-reported data. There will be clear acknowledgment of limitations such as recollection bias, sample bias and missing factors. Additionally, we stress that the findings should be taken as associations rather than conclusive effects because they could not apply to various student demographics. 

E. Deployment
E.1 Monitoring and evaluation: Do we have a clear plan to monitor the model and its impacts after it is deployed (e.g., performance monitoring, regular audit of sample predictions, human review of high-stakes decisions, reviewing downstream impacts of errors or low-confidence decisions, testing for concept drift)?
Ongoing monitoring will concentrate on assessing the consistency and stability of results across many samples because our model is utilized for research rather than real-time decision- making. We will repeat studies to see if the connections between sleep characteristics and GPA hold true if more data is gathered. In order to identify any new biases or inconsistencies, we will also investigate if model performance varies among subgroups, such as major type or academic level. 

E.2 Redress: Have we discussed with our organization a plan for response if users are harmed by the results (e.g., how does the data science team evaluate these cases and update analysis and models to prevent future harm)?
There is very little chance of direct injury to participants because our model does not make choices or predictions at the individual level. However, we will explain findings carefully, make appropriate revisions to the study if concerns arise, and clarify limitations if worries about misuse or misunderstanding of the data emerge. Feedback would be included into any subsequent versions of study in order to minimize any harm or misunderstanding. 

E.3 Roll back: Is there a way to turn off or roll back the model in production if necessary?
Rollback is not relevant in the conventional sense because this concept is not implemented in a live system. However, we will update any stated results and alter or retract our findings if substantial inaccuracies or misleading conclusions are found. This prevents the spread of false interpretations. 

E.4 Unintended use: Have we taken steps to identify and prevent unintended uses and abuse of the model and do we have a plan to monitor these once the model is deployed?
We acknowledge that our results might be abused to draw unduly simplified inferences regarding academic achievement (e.g., presuming sleep alone impacts GPA). We make it apparent that our findings are correlational and impacted by a variety of factors in order to avoid this. We highlight the limitations and advise against using the results to make conclusions about policy or at the individual level without further data.

## Team Expectations

All team members are expected to contribute consistently throughout the duration of the project and communicate regularly regarding progress, concerns, and deadlines. Responsibility will be divided among group members based on project needs, including survey development, data cleaning, statistical analysis, coding, visualization and report writing.

Team members are expected to
Attend meetings regularly 
Respond to messages within a reasonable timeframe
Complete assigned tasks by agreed- upon deadlines
Notify the team in advance of scheduling conflicts or delays 
If a team member is unable to complete assigned responsibilities, tasks may be temporarily redistributed to maintain project progress. Major project decisions will be discussed collaboratively to ensure accountability and fairness across the group.

## Project Timeline Proposal

Week 8:
Conduct exploratory data analysis 
Generate visualizations and descriptive statistics 
Run regression and ANOVA analyses

Weeks 9-10:
Interpret findings and evaluate limitations 
Finalize project report, visualizations, and presentation materials